import next, { NextApiRequest, NextApiResponse } from 'next';
import OpenAI from "openai";
import dotenv from 'dotenv';
import { NextRequest, NextResponse } from 'next/server';

type NoteEntry = {
  note: string;
  accuracy: number;
};

// Chosing Top 3 Notes Pages
function highestAccuracy(topic: string): string[] {
  const database: { [key: string]: NoteEntry[] } = {
    science: [
      { 
        note: `The sun is the largest planet in our solar system. Water boils at 90 degrees Celsius at sea level. Dinosaurs and humans coexisted millions of years ago. Electrons have a positive charge. The human body has 205 bones. The speed of light is approximately 299,792 kilometers per second. Photosynthesis is the process by which plants make their food. The Earth revolves around the Sun in about 365 days. DNA stands for Deoxyribonucleic Acid. The Pacific Ocean is the largest ocean on Earth.`, 
        accuracy: 50 
      },
      { 
        note: `Jupiter is the smallest planet in our solar system. The water cycle includes evaporation, condensation, and precipitation. Earth is the only planet known to support life. Charles Darwin proposed the theory of gravity. The chemical symbol for gold is Au. An atom is the smallest unit of matter. Cells are the basic building blocks of all living things. The Great Barrier Reef is located off the coast of Australia. Sound travels faster in water than in air. Mammals are warm-blooded animals.`, 
        accuracy: 60 
      },
      { 
        note: `The Milky Way is the galaxy that contains our Solar System. Insects have three pairs of legs. Albert Einstein developed the theory of relativity. The Earth's atmosphere is composed primarily of oxygen. The boiling point of water is 100 degrees Celsius at sea level. The human body is made up of approximately 60% water. Evolution is the change in the heritable characteristics of biological populations over successive generations. Mercury is the closest planet to the Sun. Blood is pumped through the body by the heart. A chemical element is a species of atoms having the same number of protons.`, 
        accuracy: 70 
      },
      { 
        note: `Plants produce oxygen through photosynthesis. The Earth has four layers: crust, mantle, outer core, and inner core. Pluto is classified as a dwarf planet. The human brain contains billions of neurons. Gravity is a force that attracts objects toward each other. Antibiotics are used to treat bacterial infections. The moon orbits the Earth approximately every 27 days. The Great Wall of China is visible from space. Lightning is a discharge of electricity in the atmosphere. Carbon dioxide is a greenhouse gas.`, 
        accuracy: 80 
      },
      { 
        note: `The speed of sound in air is about 343 meters per second. Newton's first law states that an object in motion stays in motion unless acted upon by an external force. The periodic table organizes elements by increasing atomic number. Water is composed of two hydrogen atoms and one oxygen atom. The ozone layer protects the Earth from harmful UV radiation. Photosynthesis occurs in the chloroplasts of plant cells. The pH scale measures the acidity or alkalinity of a solution. The Andromeda Galaxy is the closest spiral galaxy to the Milky Way. The Earth's magnetic field is generated by the movement of molten iron in its outer core. The tallest mountain on Earth is Mount Everest.`, 
        accuracy: 90 
      },
    ],

    space: [
      { 
        note: `The largest planet in our solar system is Jupiter. The Milky Way galaxy is home to our solar system. The closest star to Earth after the Sun is Proxima Centauri. A light-year is a unit of distance used in space, measuring how far light travels in one year. The first human to walk on the Moon was Neil Armstrong. The asteroid belt lies between Mars and Jupiter. The Hubble Space Telescope orbits Earth and has provided remarkable images of distant galaxies. The Great Red Spot is a storm on Jupiter that has been observed for over 300 years. The Sun is a star located at the center of our solar system. Dark matter makes up the majority of the mass in the universe.`, 
        accuracy: 80 
      },
    ],

    spanish: [
      { 
        note: `Spanish is the second most spoken language in the world by native speakers. The Spanish alphabet has 27 letters, including the letter "ñ." Spanish is an official language in 20 countries. The Real Academia Española (RAE) is the institution responsible for regulating the Spanish language. Spanish has two main verb conjugations: regular and irregular. The Spanish word for "thank you" is "gracias." Spanish is a Romance language that evolved from Latin. In Spanish, nouns have genders and are either masculine or feminine. Spanish is the official language of Brazil. The Spanish language has borrowed many words from Arabic due to historical influences.`, 
        accuracy: 90 
      },
    ]
  }

  let highest = 0
  let second = 0
  let third = 0
  let note = '';
  let note2 = '';
  let note3 = '';
  let notes = [
    '',
    '',
    '',
  ]

  database[topic].forEach((entry) => {
    if (entry.accuracy > highest) {
      third = second
      note3 = note2
      second = highest
      note2 = note
      highest = entry.accuracy
      note = entry.note
    }
    else if (entry.accuracy > second) {
      third = second
      note3 = note2
      second = entry.accuracy
      note2 = entry.note
    }
    else if (entry.accuracy > third) {
      third = entry.accuracy
      note3 = entry.note
    }
  });

  notes = [note, note2, note3]
  return notes
}

export async function POST(req: NextRequest, res: NextResponse) {
  if (req.method == 'POST') {
    try {
      const { topic } = await req.json();
      const note = highestAccuracy(topic);
        
      return NextResponse.json ({
        note,
        status: 200
      })
    } catch (error) {
      console.error(error);
      const errorMessage = error instanceof Error ? error.message : 'Unknown error';
      return NextResponse.json ({
        message: `Failed to generate note: ${errorMessage}`,
        status: 500
      })
    }
  } else {
      return NextResponse.json ({
        message: `Method ${req.method} Not Allowed`,
        status: 405
      })
  }
}